gateway[0]="lan"
gateway[1]="dmz"
gateway[2]="wan"
gateway[image]="netinfect/gateway"

server_1[0]="dmz"
server_1[image]="netinfect/host"

server_2[0]="dmz"
server_2[image]="netinfect/host"

client_1[0]="lan"
client_1[image]="netinfect/host"

client_2[0]="lan"
client_2[image]="netinfect/host"

attacker[0]="wan"
attacker[image]="netinfect/host"
