gateway[0]="vulnerable_net"
gateway[1]="quarantine_net"
gateway[image]="netinfect/gateway"

server_1[0]="vulnerable_net"
server_1[image]="netinfect/host"

server_2[0]="vulnerable_net"
server_2[image]="netinfect/host"

client_1[0]="vulnerable_net"
client_1[image]="netinfect/host"

quarantine[0]="quarantine_net"
